use_frameworks!

platform :ios, '9.0'

target 'LightFilterMenuView_Example' do
  pod 'LightFilterMenuView', :path => '../'

  target 'LightFilterMenuView_Tests' do
    inherit! :search_paths

    
  end
end
